"""Python side of the cross-language digest conformance vectors (T-004).

The vectors file is generated by tools/gen_digest_vectors.py. This test
recomputes every digest with the reference profile and fails on drift, so
neither language can move independently of the other.
"""
import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reference.qualification import plan_digest, record_digest, subject_digest

VECTORS = ROOT / "crates" / "hephaestus" / "tests" / "fixtures" / "digest-vectors.json"


class DigestConformance(unittest.TestCase):
    def test_vectors_match_reference_profile(self):
        for vector in json.loads(VECTORS.read_text()):
            if "synthetic" in vector:
                record = vector["synthetic"]
                label = vector["synthetic_label"]
            else:
                bundle = json.loads((ROOT / vector["fixture"]).read_text())
                record = next(r for r in bundle["records"] if r["id"] == vector["id"])
                label = f'{vector["fixture"]}:{vector["id"]}'
            self.assertEqual(record_digest(record), vector["record_digest"], label)
            self.assertEqual(subject_digest(record), vector["subject_digest"], label)
            if "plan_digest" in vector:
                self.assertEqual(plan_digest(record), vector["plan_digest"], label)


if __name__ == "__main__":
    unittest.main()
