//! Canonical JSON digest profile (T-004).
//!
//! Mirrors `reference/qualification.py`: SHA-256 over the UTF-8 encoding of
//! canonical JSON — object keys sorted (Python `sort_keys`), compact
//! separators, non-ASCII written raw (`ensure_ascii=False`), finite numbers
//! only (`allow_nan=False`).
//!
//! Cross-language conformance vectors live in
//! `tests/fixtures/digest-vectors.json`, generated by
//! `tools/gen_digest_vectors.py` and asserted by both
//! `tests/test_digest_vectors.py` (Python side) and
//! `tests/digest_conformance.rs` (Rust side).
//!
//! Known limitation, recorded honestly: Python renders floats with `repr`,
//! which can emit exponent forms (`1e-07`) that Rust formats differently
//! (`1e-7`). Digest inputs inside that range are a cross-language mismatch
//! that fails closed (digest differs → binding rejected). The conformance
//! vectors cover the fixture range; revisit before runtime use, as the
//! package README already requires.

use serde_json::{Map, Value};
use sha2::{Digest, Sha256};

/// Why a value could not be canonicalized under this profile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DigestError {
    /// `allow_nan=False` parity: non-finite numbers are rejected.
    NonFiniteNumber,
    /// Only string keys are valid JSON object keys.
    NonStringKey,
}

impl std::fmt::Display for DigestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DigestError::NonFiniteNumber => write!(f, "non-finite number in digest input"),
            DigestError::NonStringKey => write!(f, "non-string object key in digest input"),
        }
    }
}

impl std::error::Error for DigestError {}

fn write_value(value: &Value, out: &mut Vec<u8>) -> Result<(), DigestError> {
    match value {
        Value::Null => out.extend_from_slice(b"null"),
        Value::Bool(true) => out.extend_from_slice(b"true"),
        Value::Bool(false) => out.extend_from_slice(b"false"),
        Value::Number(n) => {
            let f = n.as_f64().ok_or(DigestError::NonFiniteNumber)?;
            if !f.is_finite() {
                return Err(DigestError::NonFiniteNumber);
            }
            // serde_json's Display for numbers uses shortest round-trip
            // representation, matching Python repr for fixture-range values.
            let rendered = n.to_string();
            out.extend_from_slice(rendered.as_bytes());
        }
        Value::String(s) => {
            // serde_json string escaping matches Python json.dumps for this
            // profile: ASCII control chars escaped, non-ASCII kept raw.
            let encoded = serde_json::to_string(s).expect("string serializes");
            out.extend_from_slice(encoded.as_bytes());
        }
        Value::Array(items) => {
            out.push(b'[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(b',');
                }
                write_value(item, out)?;
            }
            out.push(b']');
        }
        Value::Object(map) => {
            write_object(map, out)?;
        }
    }
    Ok(())
}

fn write_object(map: &Map<String, Value>, out: &mut Vec<u8>) -> Result<(), DigestError> {
    let mut keys: Vec<&String> = Vec::with_capacity(map.len());
    for key in map.keys() {
        keys.push(key);
    }
    // Python sort_keys: lexicographic by code point == byte order for UTF-8.
    keys.sort();
    out.push(b'{');
    for (i, key) in keys.iter().enumerate() {
        if i > 0 {
            out.push(b',');
        }
        let encoded = serde_json::to_string(key).expect("key serializes");
        out.extend_from_slice(encoded.as_bytes());
        out.push(b':');
        write_value(&map[*key], out)?;
    }
    out.push(b'}');
    Ok(())
}

/// Canonical JSON bytes for the digest profile.
pub fn canonical_bytes(value: &Value) -> Result<Vec<u8>, DigestError> {
    let mut out = Vec::new();
    write_value(value, &mut out)?;
    Ok(out)
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// `record_digest`: SHA-256 of the canonical record JSON.
pub fn record_digest(record: &Value) -> Result<String, DigestError> {
    Ok(sha256_hex(&canonical_bytes(record)?))
}

/// Receipt-reference fields omitted by name to avoid hash cycles.
const SUBJECT_OMISSIONS: [&str; 4] = [
    "execution_receipt_ref",
    "analysis_receipt_ref",
    "reproduction_receipt_ref",
    "promotion_receipt_ref",
];

/// `subject_digest`: assessment payload excluding only receipt references.
pub fn subject_digest(record: &Value) -> Result<String, DigestError> {
    let Value::Object(map) = record else {
        return record_digest(record);
    };
    let filtered: Map<String, Value> = map
        .iter()
        .filter(|(key, _)| !SUBJECT_OMISSIONS.contains(&key.as_str()))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    record_digest(&Value::Object(filtered))
}

/// `plan_digest`: registered payload excluding `status` and `registration`.
pub fn plan_digest(plan: &Value) -> Result<String, DigestError> {
    let Value::Object(map) = plan else {
        return record_digest(plan);
    };
    let filtered: Map<String, Value> = map
        .iter()
        .filter(|(key, _)| key.as_str() != "status" && key.as_str() != "registration")
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    record_digest(&Value::Object(filtered))
}
